

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Q = QtWidgets.QPushButton(self.centralwidget)
        self.Q.setGeometry(QtCore.QRect(100, 360, 41, 41))
        self.Q.setObjectName("Q")
        self.W = QtWidgets.QPushButton(self.centralwidget)
        self.W.setGeometry(QtCore.QRect(140, 360, 41, 41))
        self.W.setObjectName("W")
        self.R = QtWidgets.QPushButton(self.centralwidget)
        self.R.setGeometry(QtCore.QRect(220, 360, 41, 41))
        self.R.setObjectName("R")
        self.E = QtWidgets.QPushButton(self.centralwidget)
        self.E.setGeometry(QtCore.QRect(180, 360, 41, 41))
        self.E.setObjectName("E")
        self.U = QtWidgets.QPushButton(self.centralwidget)
        self.U.setGeometry(QtCore.QRect(340, 360, 41, 41))
        self.U.setObjectName("U")
        self.I = QtWidgets.QPushButton(self.centralwidget)
        self.I.setGeometry(QtCore.QRect(380, 360, 41, 41))
        self.I.setObjectName("I")
        self.Y = QtWidgets.QPushButton(self.centralwidget)
        self.Y.setGeometry(QtCore.QRect(300, 360, 41, 41))
        self.Y.setObjectName("Y")
        self.T = QtWidgets.QPushButton(self.centralwidget)
        self.T.setGeometry(QtCore.QRect(260, 360, 41, 41))
        self.T.setObjectName("T")
        self.A = QtWidgets.QPushButton(self.centralwidget)
        self.A.setGeometry(QtCore.QRect(120, 400, 41, 41))
        self.A.setObjectName("A")
        self.S = QtWidgets.QPushButton(self.centralwidget)
        self.S.setGeometry(QtCore.QRect(160, 400, 41, 41))
        self.S.setObjectName("S")
        self.P = QtWidgets.QPushButton(self.centralwidget)
        self.P.setGeometry(QtCore.QRect(460, 360, 41, 41))
        self.P.setObjectName("P")
        self.O = QtWidgets.QPushButton(self.centralwidget)
        self.O.setGeometry(QtCore.QRect(420, 360, 41, 41))
        self.O.setObjectName("O")
        self.G = QtWidgets.QPushButton(self.centralwidget)
        self.G.setGeometry(QtCore.QRect(280, 400, 41, 41))
        self.G.setObjectName("G")
        self.H = QtWidgets.QPushButton(self.centralwidget)
        self.H.setGeometry(QtCore.QRect(320, 400, 41, 41))
        self.H.setObjectName("H")
        self.F = QtWidgets.QPushButton(self.centralwidget)
        self.F.setGeometry(QtCore.QRect(240, 400, 41, 41))
        self.F.setObjectName("F")
        self.D = QtWidgets.QPushButton(self.centralwidget)
        self.D.setGeometry(QtCore.QRect(200, 400, 41, 41))
        self.D.setObjectName("D")
        self.L = QtWidgets.QPushButton(self.centralwidget)
        self.L.setGeometry(QtCore.QRect(440, 400, 41, 41))
        self.L.setObjectName("L")
        self.Z = QtWidgets.QPushButton(self.centralwidget)
        self.Z.setGeometry(QtCore.QRect(140, 440, 41, 41))
        self.Z.setObjectName("Z")
        self.K = QtWidgets.QPushButton(self.centralwidget)
        self.K.setGeometry(QtCore.QRect(400, 400, 41, 41))
        self.K.setObjectName("K")
        self.J = QtWidgets.QPushButton(self.centralwidget)
        self.J.setGeometry(QtCore.QRect(360, 400, 41, 41))
        self.J.setObjectName("J")
        self.V = QtWidgets.QPushButton(self.centralwidget)
        self.V.setGeometry(QtCore.QRect(260, 440, 41, 41))
        self.V.setObjectName("V")
        self.B = QtWidgets.QPushButton(self.centralwidget)
        self.B.setGeometry(QtCore.QRect(300, 440, 41, 41))
        self.B.setObjectName("B")
        self.C = QtWidgets.QPushButton(self.centralwidget)
        self.C.setGeometry(QtCore.QRect(220, 440, 41, 41))
        self.C.setObjectName("C")
        self.X = QtWidgets.QPushButton(self.centralwidget)
        self.X.setGeometry(QtCore.QRect(180, 440, 41, 41))
        self.X.setObjectName("X")
        self.verg = QtWidgets.QPushButton(self.centralwidget)
        self.verg.setGeometry(QtCore.QRect(420, 440, 41, 41))
        self.verg.setObjectName("verg")
        self.nuqta = QtWidgets.QPushButton(self.centralwidget)
        self.nuqta.setGeometry(QtCore.QRect(460, 440, 41, 41))
        self.nuqta.setObjectName("nuqta")
        self.M = QtWidgets.QPushButton(self.centralwidget)
        self.M.setGeometry(QtCore.QRect(380, 440, 41, 41))
        self.M.setObjectName("M")
        self.N = QtWidgets.QPushButton(self.centralwidget)
        self.N.setGeometry(QtCore.QRect(340, 440, 41, 41))
        self.N.setObjectName("N")
        self.ENTER = QtWidgets.QPushButton(self.centralwidget)
        self.ENTER.setGeometry(QtCore.QRect(480, 400, 91, 41))
        self.ENTER.setObjectName("ENTER")
        self.probel = QtWidgets.QPushButton(self.centralwidget)
        self.probel.setGeometry(QtCore.QRect(220, 480, 201, 41))
        self.probel.setText("")
        self.probel.setObjectName("probel")
        self.left_alt = QtWidgets.QPushButton(self.centralwidget)
        self.left_alt.setGeometry(QtCore.QRect(180, 480, 41, 41))
        self.left_alt.setObjectName("left_alt")
        self.right_alt = QtWidgets.QPushButton(self.centralwidget)
        self.right_alt.setGeometry(QtCore.QRect(420, 480, 41, 41))
        self.right_alt.setObjectName("right_alt")
        self.right_ctrl = QtWidgets.QPushButton(self.centralwidget)
        self.right_ctrl.setGeometry(QtCore.QRect(530, 480, 41, 41))
        self.right_ctrl.setObjectName("right_ctrl")
        self.left_ctrl = QtWidgets.QPushButton(self.centralwidget)
        self.left_ctrl.setGeometry(QtCore.QRect(100, 480, 41, 41))
        self.left_ctrl.setObjectName("left_ctrl")
        self.pusk = QtWidgets.QPushButton(self.centralwidget)
        self.pusk.setGeometry(QtCore.QRect(140, 480, 41, 41))
        self.pusk.setObjectName("pusk")
        self.printSc = QtWidgets.QPushButton(self.centralwidget)
        self.printSc.setGeometry(QtCore.QRect(460, 480, 71, 41))
        self.printSc.setObjectName("printSc")
        self.right_shift = QtWidgets.QPushButton(self.centralwidget)
        self.right_shift.setGeometry(QtCore.QRect(500, 440, 71, 41))
        self.right_shift.setObjectName("right_shift")
        self.backspace = QtWidgets.QPushButton(self.centralwidget)
        self.backspace.setGeometry(QtCore.QRect(500, 360, 71, 41))
        self.backspace.setObjectName("backspace")
        self.left_shift = QtWidgets.QPushButton(self.centralwidget)
        self.left_shift.setGeometry(QtCore.QRect(100, 440, 41, 41))
        self.left_shift.setObjectName("left_shift")
        self.listView = QtWidgets.QListWidget(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(100, 10, 471, 291))
        self.listView.setObjectName("listView")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(100, 310, 471, 41))
        self.lineEdit.setStyleSheet("border-color: rgb(85, 170, 255) solid 2px;\n"
"border-radius: 8px;")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_33 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_33.setGeometry(QtCore.QRect(100, 400, 21, 41))
        self.pushButton_33.setText("")
        self.pushButton_33.setObjectName("pushButton_33")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Q.setText(_translate("MainWindow", "Q"))
        self.W.setText(_translate("MainWindow", "W"))
        self.R.setText(_translate("MainWindow", "R"))
        self.E.setText(_translate("MainWindow", "E"))
        self.U.setText(_translate("MainWindow", "U"))
        self.I.setText(_translate("MainWindow", "I"))
        self.Y.setText(_translate("MainWindow", "Y"))
        self.T.setText(_translate("MainWindow", "T"))
        self.A.setText(_translate("MainWindow", "A"))
        self.S.setText(_translate("MainWindow", "S"))
        self.P.setText(_translate("MainWindow", "P"))
        self.O.setText(_translate("MainWindow", "O"))
        self.G.setText(_translate("MainWindow", "G"))
        self.H.setText(_translate("MainWindow", "H"))
        self.F.setText(_translate("MainWindow", "F"))
        self.D.setText(_translate("MainWindow", "D"))
        self.L.setText(_translate("MainWindow", "L"))
        self.Z.setText(_translate("MainWindow", "Z"))
        self.K.setText(_translate("MainWindow", "K"))
        self.J.setText(_translate("MainWindow", "J"))
        self.V.setText(_translate("MainWindow", "V"))
        self.B.setText(_translate("MainWindow", "B"))
        self.C.setText(_translate("MainWindow", "C"))
        self.X.setText(_translate("MainWindow", "X"))
        self.verg.setText(_translate("MainWindow", ","))
        self.nuqta.setText(_translate("MainWindow", "."))
        self.M.setText(_translate("MainWindow", "M"))
        self.N.setText(_translate("MainWindow", "N"))
        self.ENTER.setText(_translate("MainWindow", "ENTER"))
        self.left_alt.setText(_translate("MainWindow", "Alt"))
        self.right_alt.setText(_translate("MainWindow", "Alt"))
        self.right_ctrl.setText(_translate("MainWindow", "Ctrl"))
        self.left_ctrl.setText(_translate("MainWindow", "Ctrl"))
        self.pusk.setText(_translate("MainWindow", "#"))
        self.printSc.setText(_translate("MainWindow", "Prtsc"))
        self.right_shift.setText(_translate("MainWindow", "Shift"))
        self.backspace.setText(_translate("MainWindow", "Backspase"))
        self.left_shift.setText(_translate("MainWindow", "Shift"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
